# Generated by Django 2.2.11 on 2021-04-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='minha_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rg',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
