# Generated by Django 2.2.11 on 2021-03-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Cidade'),
            preserve_default=False,
        ),
    ]
