# Generated by Django 2.2.11 on 2021-03-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_contrato_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Empresa'),
            preserve_default=False,
        ),
    ]
