# Generated by Django 2.2.11 on 2021-03-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_propriedade_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='servico',
        ),
    ]
