# Generated by Django 2.2.10 on 2020-05-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20200503_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='propriedade',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.AlterField(
            model_name='estado',
            name='mome',
            field=models.CharField(max_length=50, verbose_name='nome do estado'),
        ),
    ]
