# Generated by Django 2.2.10 on 2020-05-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20200510_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='mome',
            new_name='nome',
        ),
    ]
