# Generated by Django 2.2.11 on 2020-08-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20200510_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
    ]
