# Generated by Django 2.2.11 on 2020-11-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cadastros.User'),
            preserve_default=False,
        ),
    ]
